#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd

while IFS=: read -r username _ userid _ _ home _; do
    # Display the required information for each user
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
    echo "------------------------------"
done < /etc/passwd
