#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username _ userid _ _ homedir shell; do
    echo "The user $username is part of the $userid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
