#!/usr/bin/env bash
# script loops from 1 to 10, displays bad luck for the 4th loop it, good luck 8th it, Best School other it
count=1
while [ $count -le 10 ]
do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
