#!/usr/bin/env bash
# script that displays numbers from 1 to 20 and displays 4  and then bad luck from China for the 4th it, 9 and then bad luck from Japan in the 9th it, 17 and then bad luck from Italy

count=1

while [ $count -le 20 ]
do
	case $count in
		4)
			echo $count
			echo "bad luck from China"
			;;
		9)
			echo $count
			echo "bad luck from Japan"
			;;
		17) 
			echo $count
			echo "bad luck from Italy"
			;;
		*)
			echo $count
			;;
	esac
	((count++))
done
