#!/usr/bin/env bash
#script that displays content of the current directory In a list format Where only the part of the name after the first dash is displayed

for file in *; do
    if [[ -f $file && $file != .* && $file == *-* ]]; then
        name="${file#*-}"
	echo "$name"
    fi
done
